name: building-and-deployment-qa

on:
  push:
    branches:
      - master
      - qa
      - features/adquirencia

  workflow_dispatch:

env:
  project_name: "bbog-cb-automation-testing"
  team: "cb" #cc-tc-cd-pv-bm-pl-pb-sd-cs-pe etc.
  language: "java" #javascript, java


jobs:
  build-qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 #Clona el repositorio en la maquina de ubuntu
      - uses: actions/setup-java@v3 #Instalación JDK java
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Install Chrome
        shell: bash
        run: |
          sh ./shell/chrome.sh

  integration-test-qa:
    runs-on: ubuntu-latest
    environment: master
    needs: [ build-qa ]
    steps:
      - uses: actions/setup-java@v3 #Instalación JDK java
        with:
          distribution: 'adopt'
          java-version: '8'
      - uses: actions/checkout@v3
      - name: Run test with gradle
        uses: gradle test
        with:
          arguments: build
      - name: Results Owasp Zap
        run: |
          cd pipeline/
          pwd
          ls
          npm i
          npm run evaluate
          npm fund
      - name: Report news
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: report saucedemo
          retention-days: 1
          path: |
            target/site/serenity/serenity-summary.html
            target/site/serenity/index.html
