name: 'build qa'
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - {uses: actions/checkout@v2}
      - {uses: actions/setup-java@v2, with: {java-version: '8', distribution: adopt}}
      - {name: 'Validate Gradle wrapper', uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b}
      - {name: 'Install Chrome', shell: bash, run: 'sh ./shells/chrome.sh'}
      - {name: 'Build with Gradle', uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7, with: {arguments: clean build --debug}}
      - {name: 'Reports gradle', uses: actions/upload-artifact@v2, with: {name: reports-Adquirencia, path: "target/site/serenity/index.html\ntarget/site/serenity/serenity-summary.html\n", retention-days: 1}}
